services:
   mongo:
      build:
         context: .
         dockerfile: Dockerfile-MongoDB
      networks:
         - prfq-network
      ports:
         - 6000:27017

   server:
      build:
         context: server
         dockerfile: ./Dockerfile
      networks:
         - prfq-network
      command: # TODO
      tty: true
      stdin_open: true
      depends_on:
         - mongo

   client:
      build:
         context: client
         dockerfile: ./Dockerfile
      networks:
         - prfq-network
      command: #TODO
      tty: true
      stdin_open: true
      depends_on:
         - server

   jenkins:
      build:
         context: 'jenkins'
         dockerfile: './Dockerfile'
      ports:
         - '8080:8080'
         - '50000:50000'
      volumes:
         - jenkins_home:/var/jenkins_home
      privileged: true
      shm_size: '2gb'

networks:
   prfq-network:
      driver: bridge

volumes:
   jenkins_home:
