apiVersion: apps/v1
kind: Deployment
metadata:
   name: prf-devops-quiz-proxy
spec:
   selector:
      matchLabels:
         app: prf-devops-quiz-proxy
   template:
      metadata:
         labels:
            app: prf-devops-quiz-proxy
      spec:
         containers:
            - name: prf-devops-quiz-proxy
              image: nginx:stable-alpine
              volumeMounts:
                 - name: nginx-config
                   mountPath: /etc/nginx/nginx.conf
                   subPath: nginx.conf
              ports:
                 - containerPort: 80
         volumes:
            - name: nginx-config
              configMap:
                 name: prf-devops-quiz-proxy-config
---
apiVersion: v1
kind: Service
metadata:
   name: prf-devops-quiz-proxy
spec:
   selector:
      app: prf-devops-quiz-proxy
   ports:
      - port: 80
   type: NodePort
